
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aotqdnwgqxxvurhkpbwn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFvdHFkbndncXh4dnVyaGtwYnduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3ODAyNTAsImV4cCI6MjA2MzM1NjI1MH0._K9C6kXmUqQDRT3yySQ_hDh_Vs6pD09g6OeABFfIoBs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  }
});
